### ISSUE TITLE
Computing features.csv and mos.csv for custom dataset

### ISSUE THREAD

**Issue by ahmad-bashir9** [zzc-1998/NR-QA-for-point-cloud#1]
Hello,

I was trying to test the method on my custom point cloud to compute SRCC, PLCC and KRCC. How can I compute features.csv and mos.csv. I guess features.csv can be obtained from demo.py with little modifications(please confirm) but mos.csv is the major issue. Please share some more information for custom point clouds. Thank you

**Comment by zzc-1998** [comment]
Yes, the features can be obtained via demo.py.
The mos indicates the mean opinion score, which is usually generated by the subjective experiment and considered as the ground truth (quality labels) of the point clouds. In the subjective experiment, people are invited to evaluate the point clouds and give their subjective ratings, which are the source of mos. For your custom point cloud, you should manually judge the point cloud first in terms of visual quality then you can compute SRCC, PLCC and KRCC.

**Comment by ahmad-bashir9** [comment]
Okay, thank you.
